# version: '3.8'

services:
  web:
    build: .
    command: python ./investicom/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/apps
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  prometheus:
    image: prom/prometheus:v2.14.0
    volumes:
      - ./prometheus/:/etc/prometheus
    ports:
      - 9090:9090
    networks:
      - mynetwork

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
