# version: '3.8'

services:
  web:
    build: .
    command: python ./investicom/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/apps
    ports:
      - "8000:8000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
